//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public string ApplicantEmail { get; set; }
        public string CollegeName { get; set; }
        public System.DateTime CourseCompletion { get; set; }
        public string ResumeUrl { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
