//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplicant
    {
        public string JobId { get; set; }
        public string applicantEmail { get; set; }
        public string CStatus { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual JobPost JobPost { get; set; }
    }
}
