//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPost()
        {
            this.JobApplicants = new HashSet<JobApplicant>();
        }
    
        public string JobId { get; set; }
        public string RecruiterEmail { get; set; }
        public string JobTitle { get; set; }
        public string JobLocation { get; set; }
        public Nullable<double> JobSalary { get; set; }
        public string JobDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplicant> JobApplicants { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
