//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkScout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruiter
    {
        public string RecruiterEmail { get; set; }
        public string CompanyName { get; set; }
        public string CompanyWebsiteUrl { get; set; }
        public string Designation { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
